# Generated by Django 4.1 on 2022-08-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Pergunta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Mostrar'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='Opções')),
                ('votes', models.IntegerField(default=0, verbose_name='Votos')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.question')),
            ],
        ),
    ]
